# In _config.yml
title: Introduction to Speech Processing
author: Tom Bäckström, Okko Räsänen, Abraham Zewoudie, Pablo Pérez Zarazaga, Liisa Koivusalo, Sneha Das, Esteban Gómez Mellado, Mariem Bouafif Mansali, Daniel Ramos, Mohammad Hassan Vali
logo: logo.png
execute:
  execute_notebooks: auto

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

html:
  extra_footer: |
    <p>
    <img src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" style="border-width: 0;" alt="Creative Commons License" />
    This work is licensed under a <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.    
    </p>
sphinx:
  config:
    html_show_copyright: false
    bibtex_reference_style: author_year
    language: en
  extensions:
    - sphinxcontrib.mermaid
    
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

# Information about where the book exists on the web
repository:
  url                       : https://github.com/Speech-Interaction-Technology-Aalto-U/itsp
  branch                    : master 
  
launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  binderhub_url: "https://mybinder.org" 
  colab_url: "https://colab.research.google.com"
